name: Publish NPM

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Dry-run'
        type: boolean
        required: false

run-name: >-
  Publish
    ${{ github.ref_name && format('{0}', github.ref_name) || format('') }}
    ${{ inputs.dry-run && format('[🚫 Dry-Run]') || format('') }}

permissions:
  packages: write

concurrency: publish-npm

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install
        uses: ./.github/actions/node-install
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: pnpm build

      - name: Configure NPM
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc

      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
            ARGS="--yes "
            if [[ "${{ inputs.dry-run }}" == "true" ]]; then
              ARGS+="--dry-run "
            fi
            
            MAX_RETRIES=3
            RETRY_COUNT=0
            
            while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
              if pnpm ci:publish $ARGS; then
                echo "Published successfully"
                break
              else
                RETRY_COUNT=$((RETRY_COUNT+1))
                if [ $RETRY_COUNT -lt $MAX_RETRIES ]; then
                  echo "Publish failed, retrying in 60 seconds..."
                  sleep 60
                else
                  echo "Publish failed after $MAX_RETRIES attempts"
                  exit 1
                fi
              fi
            done
